### ISSUE TITLE
--list-layers is required

### ISSUE THREAD

**Issue by isomerase** [kesara/deepdreamer#2]
Hi @kesara,

I pulled your changes and now when I try to run ``python deepdreamer.py [IMG]`` I get this error:

`deepdreamer.py: error: one of the arguments image --list-layers is required`

I don't know much about argument parsing, but is there a way to set a default?

**Comment by kesara** [comment]
Hi @isomerase,

I can't reproduce this error.
`python deepdreamer.py image.jpg` works fine for me.
https://github.com/kesara/deepdreamer/blob/master/deepdreamer.py#L55-L59 take care of this.

**Comment by isomerase** [comment]
False alarm, sorry! I had checked out a revision locally.
