### ISSUE TITLE
merge with DeepDreamAnim?

### ISSUE THREAD

**Issue by isomerase** [kesara/deepdreamer#5]
Hey @kesara there's a pretty sweet project at samim23/DeepDreamAnim which wouldn't be hard to merge into this project. What do you think?

**Comment by kesara** [comment]
Interesting. I'll be looking into that.

**Comment by kesara** [comment]
[feature/animate](https://github.com/kesara/deepdreamer/tree/feature/animate) branch added.

**Comment by kesara** [comment]
Hey @isomerase, After looking at DeepDreamAnim, I thought it would be much easier to use ffmpeg as DeepDreamAnim does.
I've committed some changes to [feature/animate](https://github.com/kesara/deepdreamer/tree/feature/animate). Feel free to test. :)
